version: "3.9"

services:
  nginx:
    container_name: nginx
    extra_hosts:
      - "rmatsuba.42.jp:127.0.0.1"
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: always
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: always
    env_file:
      - .env
    secrets:
      - mysql-db-password
      - mysql-db-root-password

  wordpress:
    container_name: wordpress
    extra_hosts:
      - "rmatsuba.42.jp:127.0.0.1"
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress
    volumes:
      - wordpress_files:/var/www/html
    depends_on:
      - mariadb
    networks:
      - inception
    restart: always
    env_file:
      - .env
    secrets:
      - db-password
      - wp-admin-password
      - wp-user-password

volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: "none"
      # device: "/home/rmatsuba/data/mariadb"
      device: "/Users/ryutaro320515/development/inception/data/mariadb"
      o: "bind"
  wordpress_files:
    driver: local
    driver_opts:
      type: "none"
      # device: "/home/rmatsuba/data/wordpress"
      device: "/Users/ryutaro320515/development/inception/data/wordpress"
      o: "bind"

networks:
  inception:
    driver: bridge


secrets:
  mysql-db-password:
    file: ../secrets/mysql_db_password.txt
  mysql-db-root-password:
    file: ../secrets/mysql_db_root_password.txt
  db-password:
    file: ../secrets/db_password.txt
  wp-admin-password:
    file: ../secrets/wp_admin_password.txt
  wp-user-password:
    file: ../secrets/wp_user_password.txt

